import './globals.css'
import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'

import Navbar from '@/components/Navbar'

const defaultFont = DM_Sans({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={defaultFont.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
